### ISSUE TITLE
[Enhancement] multi-languages support

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#18]
It's not necessary but it would be nice, if you want I can translate into French.

**Todo list:**
- [x] Create generic language structure with typescript interface for validation
- [x] Enable string interpolation support for some code sections
- [x] Rewrite Fuzzy Matcher to use callbacks to transfer information
- [x] Rewrite parser component into generic form
- [x] Enable markdown support for some code sections
- [x] Rewrite instructions in markdown
- [x] Write SCSS style for markdown
- [x] Add a way to insert Angular SVG component
- [x] Add code highlight
- [x] Rewrite all renderer components to use global language variable
- [x] Rewrite all renderer services to use global language variable
- [x] Rewrite all renderer templates to use global language variable
- [x] Rewrite all renderer libraries to use global language variable
- [x] Add option to select language

**Comment by FrogTheFrog** [comment]
Todo list:
- [x] Create generic language structure with typescript interface for validation
- [x] Enable string interpolation support for some code sections
- [ ] Enable markdown support for some code sections
- [ ] Rewrite all renderer components to use global language variable
- [ ] Rewrite all rendere services to use global language variable
- [ ] Rewrite all renderer templates to use global language variable
- [ ] Rewrite all renderer libraries to use global language variable
- [ ] Rewrite Fuzzy Matcher to use callbacks to transfer information
- [ ] Add option to select language
