### ISSUE TITLE
Move image providers from main thread to web workers

### ISSUE THREAD

**Issue by FrogTheFrog** [SteamGridDB/steam-rom-manager#25]
Should reduce app stutter and allow to implement more performance inpacting image providers in the future.

**Todo list:**
- [x] Split Fuzzy matcher into 2 parts. One for retrieving title list, other for matching.
- [x] Make a generic provider structure to work on web workers.
- [x] Add pipes/callbacks for IPC (Inter Process Communication).
- [x] Fix the `worker-loader` module error.
- [x] Rewrite SteamGridDB provider to work with new API.
- [x] Rewrite retrograming.cloud provider to work with new API.
- [x] Rewrite consolegrid provider to work with new API.

**Comment by HEspoke** [comment]
I have been working with the creator of SteamGridDB that you reference on your github landing page for SRM. I spent yesterday uploading my grid images and labeling them successfully. If there are any grid images that don't populate and you think that the 'title'    is correct then let me know and I can look into it. Great work as always, keep it up @FrogTheFrog

**Comment by FrogTheFrog** [comment]
Finally got a generic structure for retrieving image data in a web worker:

```
import { GenericProvider, GenericProviderManager } from "./generic-provider";

class SteamGridDbProvider extends GenericProvider {
    retrieveUrls() { //Entry point
        console.log('Do stuff here with ', this.proxy.title);

        if (this.proxy.filter){
            //Filter titles
            this.proxy.fuzzyMatcher.fuzzyEqual(...)
        }

        this.proxy.error(...); //Notify about error
        this.proxy.image(...); //Send image data
        this.proxy.timeout(...); //Send timeout request
        
        this.proxy.completed(); //Done retrieving data
    }

    stopUrlDownload() {
        console.log('User wants to abort. Ignore user or stop everything and call "this.proxy.completed"');
    }
}

new GenericProviderManager(SteamGridDbProvider);
```
