### ISSUE TITLE
TODO memo before 2.1.0 release

### ISSUE THREAD

**Issue by FrogTheFrog** [SteamGridDB/steam-rom-manager#35]
Before big push:
- [x] proofread markdown for ducks and quacks;
- [x] update changelog;

Before PR:
- [x] close all milestone issues;
- [x] update github `readme` (with mp4 support possibly);
- [x] move github page to subfolder;
- [x] play with docker, find out what's wrong with it;
- [x] make another more technical `readme` for building stuff.
